.gitmodules
.travis.yml
datalad_neuroimaging/tests/test_dicomconv.py
datalad_neuroimaging/tests/utils.py

This will be instrumental for testing anything related to metadata. The current setup relies on the `///` which is outdated, or toy examples with limited scope. We need a full featured dataset with all bells and whistles that we can have.

Fish helpers out of #7 to generate a BIDS dataset from DICOM as a test fixture

---

datalad_neuroimaging/tests/test_bids2scidata.py

As soon as we have new-style metadata exposed somewhere, this command can easily be tested via installing from the `///` dataset.

bids2scidata test when new metadata becomes available

---

datalad_neuroimaging/extractors/bids.py

An installation was missing scipy (because https://github.com/INCF/pybids/issues/174), and suddenly the metadata changed structure. I was not aware, because I made it ignore all errors, including ImportErrors. not good.

BIDS extractor hides any issue with pybids

---

datalad_neuroimaging/__init__.py
datalad_neuroimaging/bids2scidata.py

see https://github.com/datalad/datalad/issues/2514 for the reference/discussion
also added import of datalad's setup_package so we get similar tests behavior etc

BF(workaround): raise explicit RuntimeError if running within source tree

---

datalad_neuroimaging/extractors/bids.py
datalad_neuroimaging/extractors/tests/test_bids.py
docs/examples/nipype_workshop_dataset.sh
setup.py

in 0.6 pybids
- dropped installation schemes
- broke API
may be https://github.com/INCF/pybids/pull/218/files would return installation
scheme to improve compatibility, but I guess we should no longer rely on
it anyways

BF: make compatible with pybids 0.6.4

---

datalad_neuroimaging/extractors/bids.py
datalad_neuroimaging/extractors/tests/test_bids.py
datalad_neuroimaging/tests/test_aggregation.py
datalad_neuroimaging/tests/test_search.py

Various BIDS-related improvements

---

datalad_neuroimaging/extractors/dicom.py
datalad_neuroimaging/extractors/tests/test_dicom.py

Since pydicom 1.0 MultiValue is not longer a subclass of list but of
MutableSequence.  list is also subclass of MutableSequence but I have
decided to retain it in condition for clarity
Closes #49

BF: dicom - handle dcm.multival.MultiValue (or any MutableSequence) as a list

---

CHANGELOG.md
datalad_neuroimaging/bids2scidata.py
datalad_neuroimaging/extractors/bids.py
datalad_neuroimaging/extractors/tests/test_bids.py
datalad_neuroimaging/tests/test_search.py
setup.py

But having done it not sure if I we want to keep compatibility with
previuos versions since it is not only that API changed, but also their
annotation. At the least  "type" is now a non-specific "suffix", and
"modality" became a "datatype".  Whenever I am ok with "datatype",
loosing "type" is probably suboptimal although makes sense within
BIDS itself.
But having those changes in mind, it might be better to just demand
0.7.0 and remove compatibility layer.
Also I think it is time to start encoding some kind of "version" of
PyBIDS convention on top of what version of BIDS actual dataset
conforms with.  Since BIDS does not necessarily always gives corresponding
consistent namings aligned with PyBIDS I feel that we could still
have similar renamings in the future
Closes: #43

RF: make compatible also with recent pybids 0.7.0

---

.travis.yml
setup.py

BF: revert to the original way of installing package data to install cfg_bids; test out of source

---

setup.py

To keep it usable until #67 is addressed.

BF(workaround): no pybids 0.9.x for us yet

---

setup.py

Now that https://github.com/bids-standard/pybids/pull/444 was merged/released

RF: demand pybids >=0.9.2.

---

docs/examples/nipype_workshop_dataset.sh

In 0.12.x, `datalad save` no longer accepts --super-datasets.  In a
blind to make the example compatible with the latest DataLad, use the
--dataset=^ shortcut instead.
Note that there are other spots in the example that should be updated
for the 0.12.x release (e.g., use of `datalad add`).  This is just a minimal
attempt to get it passing.
Re: https://github.com/datalad/datalad-neuroimaging/pull/74#issuecomment-580340491
---
Note: A test failure due to issue resolved by gh-74 is still expected.

MNT: nipype_workshop_dataset: Update save() call for DataLad 0.12

---

datalad_neuroimaging/bids2scidata.py

This popped up in the "DeprecationWarning -> error" run from datalad/datalad#3618: https://travis-ci.org/datalad/datalad/jobs/576041485#L1241

MNT: bids2scidata: Use .iloc instead of deprecated .ix

---

datalad_neuroimaging/extractors/dicom.py

pydicom renamed PersonName3 to PersonName in 2.0.0.
(Closes #85)

Fix for pydicom >= 2.0.0

---

.appveyor.yml

Enables a new codecov uploader after the old one was fully replaced by codecov. Fixes #91 
I followed [codecov's blog post](https://about.codecov.io/blog/introducing-codecovs-new-uploader/) and an [analogous change in datalad](https://github.com/datalad/datalad/commit/1b542bd135cbdb2982d5e2035cd1757ec5ec27dd). I'm not sure why on windows the codecov call is done with `-f "coverage.xml"` and on linux without, but that's how it's done in datalad.

Enable new codecov uploader in Appveyor CI

---

formatters.py
setup_support.py

The documentation for the commands contain dashes that should be spaces, ie:
`datalad-bids2scidata` should be `datalad bids2scidata`
This applies a fix that was made for other docs (https://github.com/datalad/datalad/pull/1761).
(Closes #89)

BF:Docs: replace incorrect dashes with spaces in command names

---

.readthedocs.yaml

Added a `.readthedocs.yaml` file to make readthedocs use Python 3.8 (instead of 3.7) when building documentation. On 3.7 (default) the build failed when trying to install the package dependencies due to version mismatch (pandas / numpy).
This should cause the docs to start building again. Fixes #98

Use python 3.8 for building docs

---

.appveyor.yml
.github/workflows/test_crippledfs.yml
Makefile
datalad_neuroimaging/__init__.py
datalad_neuroimaging/conftest.py
datalad_neuroimaging/extractors/tests/test_bids.py
datalad_neuroimaging/extractors/tests/test_bids_dataset.py
datalad_neuroimaging/extractors/tests/test_dicom.py
datalad_neuroimaging/extractors/tests/test_nidm.py
datalad_neuroimaging/extractors/tests/test_nifti1.py
datalad_neuroimaging/resources/procedures/cfg_bids.py
datalad_neuroimaging/tests/test_aggregation.py
datalad_neuroimaging/tests/test_bids2scidata.py
datalad_neuroimaging/tests/test_dicomconv.py
datalad_neuroimaging/tests/test_procedure.py
datalad_neuroimaging/tests/test_register.py
datalad_neuroimaging/tests/test_search.py
datalad_neuroimaging/tests/utils.py
requirements-devel.txt
setup.cfg

for the failing test -- we might be doomed to skip it for now, but we cannot really delay that long
- skipped also most of the tests on crippled fs. Not surprisingly they all are already marked as known to fail on windows
- in those files which touched, did isort to bring some consistency

RF: use pytest, remove restriction on datalad version

---

datalad_neuroimaging/bids2scidata.py
datalad_neuroimaging/extractors/bids.py
datalad_neuroimaging/extractors/bids_dataset.py
datalad_neuroimaging/extractors/dicom.py
datalad_neuroimaging/extractors/nidm.py
datalad_neuroimaging/extractors/nifti1.py
datalad_neuroimaging/tests/test_aggregation.py
datalad_neuroimaging/tests/test_dicomconv.py
datalad_neuroimaging/tests/test_procedure.py
datalad_neuroimaging/tests/test_search.py
datalad_neuroimaging/tests/utils.py
setup.cfg

This PR adapts the parts of `datalad_neuroimaging` that used the old metadata code, i.e. the code contained in `datalad.metadata`, to the new location of this code, i.e. `datalad_deprecated.metadata`.

Adapt to the move of metadata-code from `datalad` to `datalad-deprecated`

---

.appveyor.yml
.readthedocs.yaml

Switched macOS appveyor build from "macOS" to "macos-monterey" to avoid stalling on older versions (following https://github.com/datalad/datalad-extension-template/pull/50). Fixes #116 
Added instruction to install this package before building docs to readthedocs config. The config is needed to specify Python version, and apparently now also needs to include dependency specification.  Fixes #117

Update docs and CI build configuration

---

datalad_neuroimaging/resources/procedures/cfg_bids.py

Mentioned on the matrix datalad channel.
BIDS supports:
- `README`
- `README.txt`
- `README.rst`
- `README.md`
https://bids-specification.readthedocs.io/en/latest/modality-agnostic-files.html#readme
This PR aims to make bids config reflect that.
Do not annex license file
- `LICENSE`
https://bids-specification.readthedocs.io/en/latest/modality-agnostic-files.html#license
Do not annex the bids-validator config
- `.bids-validator-config.json`
https://github.com/bids-standard/bids-validator#configuration
Even though users may name this file differently, it may make sense to support the default name.

[ENH] do not annex typical top files in BIDS datasets

---

.readthedocs.yaml

Read the Docs projects created before Oct 20, 2020 (like this one) use Sphinx 1.8.x. New projects use the latest version ([docs](https://docs.readthedocs.io/en/stable/build-default-versions.html)). Using default build requirements seems to have caused complex dependency conflicts. The only way to override these defaults seems to be through the .readthdocs.yaml config file.
The change introduced here will tell RtD to perform `pip install -e. [devel-docs]`. This relies on the fact that our setup.cfg already defines a loosely pinned (>=) sphinx dependency. Alternatively, we could introduce a dedicated requirements file for documentation, and use "requirements" key in python.install section ([docs](https://docs.readthedocs.io/en/stable/config-file/v2.html)). But here we rely on what's already …

Add extra requirements to RtD config

---

datalad_neuroimaging/extractors/bids_dataset.py

This PR:
- Improves results handling of `get_required_content`: yields impossible results instead of raising exceptions; yields results for more test cases than before (addresses https://github.com/datalad/datalad-neuroimaging/issues/122)
- Removes requirement of `participants.tsv` file (addresses https://github.com/datalad/datalad-neuroimaging/issues/121)
- Removes the option to search for the BIDS dataset root location further down in the filetree of the dataset passed to the `meta-extract` command, since this caused problems when using the extractor in a workflow on super-sub-dataset hierarchy. See https://github.com/datalad/datalad-neuroimaging/issues/123, for which the outcome may lead to an additional PR.

ENH: improvements for using `bids_dataset` extractor in workflows

---

.datalad-release-action.yaml
.github/workflows/add-changelog-snippet.yml
.github/workflows/release.yml
CHANGELOG.md
changelog.d/pr-130.md
changelog.d/scriv.ini
changelog.d/templates/entry_title.md.j2
changelog.d/templates/new_fragment.md.j2

Closes #127.
To do before merging:

Set up releasing workflows

---

.appveyor.yml
.github/workflows/codespell.yml
Makefile
_datalad_buildsupport/formatters.py
changelog.d/pr-131.md
datalad_neuroimaging/__init__.py
datalad_neuroimaging/bids2scidata.py
datalad_neuroimaging/extractors/nifti1.py
datalad_neuroimaging/extractors/tests/test_nifti1.py
datalad_neuroimaging/tests/test_search.py
formatters.py
pyproject.toml

Strangely codespell didn't pick up `millimiter` in some files :-/

Add codespell config and workflow, and use it to typos found throughout the codebase

---

changelog.d/pr-134.md
datalad_neuroimaging/extractors/nifti1.py

Should address failures observed in datalad-extensions testing so I will mark for release if passes

BF: Explicitly cast to simple float from numpy.float32 which is now returned by smth (nibabel?)

---

.github/workflows/docbuild.yml
_datalad_buildsupport/setup.py
changelog.d/pr-136.md
docs/source/usecases/index.rst
pyproject.toml

setuptools.errors were introduced in 59.0.0 release.
See https://github.com/pypa/setuptools/issues/5000 for more rationale etc.

BF: use setuptools.errors.OptionError instead of now removed import of distutils.DistutilsOptionError
